// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5rI1g3l7ZwNcxHKzM5uRat9BeqtDhxs',
    appId: '1:309891937797:web:2e2b3cda69bc5b8fa4ce6c',
    messagingSenderId: '309891937797',
    projectId: 'xyz-project-c1bab',
    authDomain: 'xyz-project-c1bab.firebaseapp.com',
    storageBucket: 'xyz-project-c1bab.firebasestorage.app',
    measurementId: 'G-RYRH76KJXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVm57TVjC-syIWWvl7LqmAYMwG27oqqLI',
    appId: '1:309891937797:android:6811070190cc07dea4ce6c',
    messagingSenderId: '309891937797',
    projectId: 'xyz-project-c1bab',
    storageBucket: 'xyz-project-c1bab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEd-MJCSlVLXEzHwUMVlGTo4dchS8W72M',
    appId: '1:309891937797:ios:deaa7d3d272b7ec4a4ce6c',
    messagingSenderId: '309891937797',
    projectId: 'xyz-project-c1bab',
    storageBucket: 'xyz-project-c1bab.firebasestorage.app',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEd-MJCSlVLXEzHwUMVlGTo4dchS8W72M',
    appId: '1:309891937797:ios:deaa7d3d272b7ec4a4ce6c',
    messagingSenderId: '309891937797',
    projectId: 'xyz-project-c1bab',
    storageBucket: 'xyz-project-c1bab.firebasestorage.app',
    iosBundleId: 'com.example.flutterFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE5rI1g3l7ZwNcxHKzM5uRat9BeqtDhxs',
    appId: '1:309891937797:web:654c2b608c8efc15a4ce6c',
    messagingSenderId: '309891937797',
    projectId: 'xyz-project-c1bab',
    authDomain: 'xyz-project-c1bab.firebaseapp.com',
    storageBucket: 'xyz-project-c1bab.firebasestorage.app',
    measurementId: 'G-24XKSYVL38',
  );
}
