// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Kk4xkqkl1p_hW8Ys-eMoXdjD6BBlcl8',
    appId: '1:259064149741:web:1a48b8d66de3a30928bee4',
    messagingSenderId: '259064149741',
    projectId: 'flutter-fire-pro',
    authDomain: 'flutter-fire-pro.firebaseapp.com',
    storageBucket: 'flutter-fire-pro.firebasestorage.app',
    measurementId: 'G-36SQVQ1F0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQX2oUuDqA1AZXX-3mHmvcQXHnv7X3JCU',
    appId: '1:259064149741:android:2691b48576f2f5e828bee4',
    messagingSenderId: '259064149741',
    projectId: 'flutter-fire-pro',
    storageBucket: 'flutter-fire-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdCtQYhGOH1tDJ2l6Ol7yWUn5TJrQuUBg',
    appId: '1:259064149741:ios:6891fcab39a8021c28bee4',
    messagingSenderId: '259064149741',
    projectId: 'flutter-fire-pro',
    storageBucket: 'flutter-fire-pro.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirePro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdCtQYhGOH1tDJ2l6Ol7yWUn5TJrQuUBg',
    appId: '1:259064149741:ios:6891fcab39a8021c28bee4',
    messagingSenderId: '259064149741',
    projectId: 'flutter-fire-pro',
    storageBucket: 'flutter-fire-pro.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirePro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Kk4xkqkl1p_hW8Ys-eMoXdjD6BBlcl8',
    appId: '1:259064149741:web:8ece60d277a0dc3628bee4',
    messagingSenderId: '259064149741',
    projectId: 'flutter-fire-pro',
    authDomain: 'flutter-fire-pro.firebaseapp.com',
    storageBucket: 'flutter-fire-pro.firebasestorage.app',
    measurementId: 'G-PMZPSK70GN',
  );
}
